# multi-line script to build the project
components:
    jwt:
        script: |
            call dotnet build -c release --framework net8.0 .\src\Microsoft.IdentityModel.JsonWebTokens\Microsoft.IdentityModel.JsonWebTokens.csproj

        arguments:
            --application.options.outputFiles .\src\Microsoft.IdentityModel.JsonWebTokens\bin\release\net8.0\

# default arguments that are always used on crank commands
defaults: --config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true --application.framework net7.0  

# the first vaule is the defualt if none is specified
profiles:
    windows:
        description: INTEL/Windows 28 Cores
        arguments: --profile aspnet-citrine-win

benchmarks:
    NoMvcAuth:
        description: NoMvcAuth
        arguments: --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/Mvc/benchmarks.jwtapi.yml --scenario NoMvcAuth
